name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
Create-Second-Job:    
  runs-on: ubuntu-latest
  steps:
    - run: echo "ğŸ‰ ${{ github.actor }}"
    - run: echo "ğŸ§ DEU CERTO A CRIAÃ‡ÃƒO DO SEGUNDO JOB!!!"